#Include, D:\Misc Development\AHKScripts\Utilities\ImageCapture\ImgCap.ahk
#SingleInstance, Force
SetWorkingDir, %A_ScriptDir%

checkPin() {

    t1:=A_TickCount, X:=Y:=""

    Text:="|<>*89$101.zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzy00000Dzzzzzzzzzy000000Tzzzzzzzzzw00003kzzzzzzzzzzs003zzVzzzzzzzzzzk07zzz3zzzzzzzzzzU01zzy7zzzzzzzzzz000DzwDzzzzzzzzzy0000TsTzzzzzzzzzw0007zkTzzzzzzzzzs003zzUzzzzzzzzzzk00HzzVzzzzzzzzzzU03zzy3zzzzzzzzzz057TwQ7zzzzzzzzzy00000sTzzzzzzzzzw00201szzzzzzzzzzs0001zlzzzzzzzzzzk001zz1zzzzzzzzzzk007zy3zzzzzzzzzzU01zzy7zzzzzzzzzz01zDU0Dzzzzzzzzzz3w0000Dzzzzzzzzzy1w0000TzzzzzzzzzwD00006Dzzzzzzzzzs00001T7zzzzzzzzzk0000Cz7zzzzzzzzzU000wxzXzzzzzzzzz0007UMzlzzzzzzzzy00001lzkzzzzzzzzzE0003XjsTzzzzzzzzs00016Tzzzzzzzzzzk000CAjzzzzzzzzzzk003yTzzzzzzzzzzzU00kyyVzzzzzzzzzzU010001zzzzzzzzzz001U009zzzzzzzzzr00k003nzzzzzzzzz70Q061zbzzzzzzzzwCR004DzDzzzzzzzzsC0008zyTzzzzzzzzsk0001zwzzzzzzzzyw0000TztzzzzzzzzxU0053zznzzzzzzzzv003iTzzbzzzzzzzzm07zXzzzDzzzzzzzzY7zxrzzyTzzzzzzzz7DzzzzzwzzzzzzzzyATzzzzztzzzzzzzzyMzzzzzzrzzzzzzzzwvzzzzzzDzzzzzzzzszzzzzzyDzzzzzzzzlzzzzzzUzzzzzzzzznzzzzzs3zzzzzzzzzbzzzzy0DzzzzzzzzzDzzzzU1zzzzzzzzzyTzzzs0Dzzzzzzzzzyzzzy03zzzzzzzzzzxzzzU0Tzzzzzzzzzzvzzs03zzzzzzzzzzzzzy00TzzzzzzzzzzzzzU07zzzzzzzzzzzzzw01zzzzzzzzzzzzzz00Tzzzzzzzzzzzzzs07zzzzzzyCDzzzzzk1zzzzzzzkcDzzzzzUDzzzzzzyt7Dzzzzy3zzzzzzzkCETzzzzvzzzzzzzzglzTzzzzzzzzzzzzy6XSzzzzzzzzzzzzzy3MjzzzzzzzzzzzzzCszzzzzzzzzzzzzzsza7zzzzzzzzzzzzzVTyTzzzzzzzzzzzzy1zzzzzzzzzzzzzzzxUzzzzzzzzzzzzzzzk4zzzzzzzzzzzzzzzYJzzzzzzzzzzzzzzzUlzzzzzzzzzzzzzzzUnzzzzzzzzzzzzzzzk7zkzzzzzzzzzzzzzzzwEzzzzzzzzzzzzzzzjNzxzzzzzzzzzzzzyHbzvTzzzzzzzzzzzwaSTzzzzzzzzzzzzzk0zzzzzzzzzzzzzzzZtzzzzzzzzzzzzzzz1nzzzzzzzzzzzzzzwTbzzTzzzzzzzkDzzwzDzyzzzzzzzz1T3zzrzzrzzzzzzzy4M7zTzzzzzzzzzzzwEk7yzzzzzzzzzzzz11k7xzzzzzzzzzzzyE7U7vzzzzzzzzzzzXzz01vzzzzzzzzzzzzsz00Tzzzzzzzzzzzzzyk0zzzzzzzzzzzzwzwU1zzzzzzzzzzzztzk07zzzzzzzzzzzzrzU0Dzzzzzzzzzzzzzz00zzzzzzzzzzzzzzw03zzzzzzzzzzzzzzk0Dzzzzzzzzzzzzzzk1zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzs1zzzzzzzzzzzzzzzU4zzzzzzzzzzzzzzw0CTzzzzzzzzzzzzzk01TzzzzzzzzzzzzzU00Tzzzzzzzzzzzzy021zzzzzzzzzzzzzw04Dzzzzzzzzzzzzzk0XjzzzzzzzzzzzzzU0Txzzzzzzzzzzzzz07zvzzzzzzzzzzzzz0Tvzzzzzzzzzzzzzw0zRzzzzzzzzzzzzzw1bTzzzzzzzzzzzzzs27zzzzzzzzzzzzzzkgDzzzzzzzzzzzzzzxgbzzzzzzzzzzzzzzl3Tzzzzzzzzzzzzzzyzzzzzzzzzzzzzzzzwzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzs"

    if (ok:=FindText(X, Y, 2381-150000, 578-150000, 2381+150000, 578+150000, 0, 0, Text))
    {
        return True
    } else {
        return False
    }
}